name: Deploy our website

on:
  workflow_dispatch

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check AWS CLI
        run: |
          aws --version
      - name: Run Deployment
        run: |
          echo Hey I startet a deployment
