name: Deploy our website

on:
  workflow_dispatch

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check AWS CLI
        run: |
          aws --version
      - name: Run Deployment
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1
        run: |
          echo Hey I startet a deployment
          mkdir ~/.aws
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET" >> ~/.aws/credentials
          echo "aws_session_token=$AWS_SESSION_TOKEN" >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config          
          aws s3api list-buckets
